### ISSUE TITLE
More information needed for Resolve patient duplicate message

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#14]
https://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/ITI-104.html#23104422-message-semantics is missing explanation on how to perfom the conditional update. Do we update only the survivor? Only the deprecated? Why not both?

**Comment by oliveregger** [comment]
In Message Semantics it is mentioned 'A Patient Identity Source initiates a FHIR request using HTTP PUT ' and below in Patient Resource constraints it is mentioned: A link of type ‘replaces’ SHALL be added with the identifier pointing to the duplicate record.

Do you have a suggestion what could do to improve the explanation?

>Do we update only the survivor? 
Yes,  as it it done for PIX V2, PIX V3 wen send the updated information (surviving identifier and link to the duplicate identifier).

>Only the deprecated? 
No, otherwise it would not be possible to group with V2, V3.

>Why not both?
We require the survivor. Both is not required since the Patient Identifier Cross-reference Manager has already all information to do the cross-referencing. We have added the sentence 'A second message with a link of type ‘replaced-by’ MAY be sent for the duplicate record with the identifier pointing to the surviving identifier.' if the  Patient Identifier Cross-reference Manager would store Patient Resources.

**Comment by oliveregger** [comment]
>A link of type ‘replaces’ SHALL be added with the identifier pointing to the duplicate record. A second message with a link of
>type ‘replaced-by’ MAY be sent for the duplicate record with the identifier pointing to the surviving identifier.

At the telco was decided to switch to the type of 'replaced-by' to follow the PMIR model that you update the subsumed (resolved) patient identifier. We remove the replaces link. We then have only one message to do resolve duplicate. 

See also https://www.hl7.org/fhir/patient.html#dup-records
