### ISSUE TITLE
Volume 1 page is now a purple rectangle

### ISSUE THREAD

**Issue by obellamouhuet** [IHE/ITI.PIXm#47]
Today when I open volume 1 there is no content, only a purple rectangle. I guess some styling change went wrong.

**Comment by JohnMoehrke** [comment]
I found a fix. Just adding a bare div at the very top of the file makes this go away. I presume there is something strange going on that we will eventually need to figure out. But for now, it is fixed. this bare div will not cause trouble if the root cause is ever found, but it will look odd to our future selves.

While trying to figure this out, I did do major cleanup of the formatting of volume 1, and more consistent use of plantuml. Thus getting rid of some unneeded images, and some unneeded image-source.
* Header levels were one header too deep, so dropped everything one letter
* changed all the text to be typical page (80 ish characters). This is not needed, but will make github changes in the future more specific, as the change would be to the one or two lines, rather than the whole paragraph. not necessary, but nice to do.
* changed to always using plantuml auto generation
* changed to normal quotes. There was many places where special quotes were used. I don't think this had any effect, but these are the proper quotes.
